# Generated by Django 4.2.6 on 2023-10-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_slider_shortdescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ('updated',), 'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='shortdescription',
            field=models.CharField(max_length=50),
        ),
    ]
