# Generated by Django 4.2.6 on 2023-10-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_slider_options_alter_slider_shortdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='post/'),
        ),
    ]
