# Generated by Django 4.2.6 on 2023-10-11 07:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_slider_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
