# Generated by Django 4.2.6 on 2023-10-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_menuitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItem',
            new_name='Menu',
        ),
    ]
