# Generated by Django 4.2.6 on 2023-10-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_sub_category',
            field=models.BooleanField(default=False, verbose_name='Sub Category'),
        ),
    ]
