# Generated by Django 4.2.6 on 2023-10-14 19:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_is_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('photo', models.ImageField(upload_to='product/photos')),
                ('price', models.FloatField()),
                ('available', models.CharField(choices=[('1', 'IN_STOCK'), ('0', 'OUT_OF_STOCK')], default='1')),
                ('short_description', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('tags', ckeditor.fields.RichTextField()),
                ('additional_information', ckeditor.fields.RichTextField(verbose_name='Additional Information')),
            ],
        ),
    ]
