# Generated by Django 4.2.6 on 2023-10-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_slug_pictures_colorchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorchoice',
            name='picture',
            field=models.ImageField(default=1, upload_to='product/photos'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
