# Generated by Django 4.2.6 on 2023-10-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(default=1, upload_to='product/photos'),
            preserve_default=False,
        ),
    ]
