# Generated by Django 4.2.6 on 2023-10-15 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_pictures_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='product/photos')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(help_text='#f456a', max_length=20, verbose_name='Color Code')),
                ('size', models.CharField(choices=[('L', 'L'), ('X', 'X'), ('XL', 'XL')])),
                ('price', models.FloatField(blank=True, help_text='blank to user the Base price ...', null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ColorChoice',
        ),
    ]
