# Generated by Django 4.2.6 on 2023-10-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_choices_delete_colorchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='price',
            field=models.FloatField(blank=True, help_text='blank to use Base price', null=True),
        ),
    ]
