# Generated by Django 4.2.6 on 2023-10-17 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_choices_inventory_product_brand_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('L', 'L'), ('X', 'X'), ('XL', 'XL')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
