# Generated by Django 4.2.6 on 2023-10-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_sizechoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='size',
        ),
    ]
