# Generated by Django 4.2.6 on 2023-10-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_choices_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizechoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.choices'),
        ),
        migrations.AlterField(
            model_name='sizechoice',
            name='size',
            field=models.CharField(),
        ),
    ]
