# Generated by Django 4.2.6 on 2023-10-18 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_rename_product_sizechoice_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizechoice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.choices'),
        ),
        migrations.AlterField(
            model_name='sizechoice',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
