# Generated by Django 4.2.6 on 2023-10-18 06:00

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_sizechoice_choice_alter_sizechoice_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizechoice',
            name='choice',
        ),
        migrations.AddField(
            model_name='sizechoice',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sizechoice',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sizechoice',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.sizechoice'),
        ),
        migrations.AddField(
            model_name='sizechoice',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sizechoice',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sizechoice',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
