# Generated by Django 4.2.6 on 2023-10-18 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_sizechoice_choice_sizechoice_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizechoice',
            name='level',
        ),
        migrations.RemoveField(
            model_name='sizechoice',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='sizechoice',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='sizechoice',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='sizechoice',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='sizechoice',
            name='choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.choices'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sizechoice',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
