# Generated by Django 4.2.6 on 2023-10-18 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_sizechoice_level_remove_sizechoice_lft_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizechoice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.choices'),
        ),
    ]
