# Generated by Django 4.2.6 on 2023-10-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_choices_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeChoice',
            new_name='Size',
        ),
    ]
