# Generated by Django 4.2.6 on 2023-10-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_rename_sizechoice_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='inventory',
        ),
        migrations.AddField(
            model_name='size',
            name='inventory',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
