# Generated by Django 4.2.6 on 2023-10-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_choices_inventory_size_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choices',
            name='price',
        ),
        migrations.AddField(
            model_name='size',
            name='price',
            field=models.FloatField(blank=True, help_text='blank to use Base price', null=True),
        ),
    ]
